{% set name = "PyDrive2" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7782320692a1a8ca830849ade876edb9e92adb5f24727af1f57f8467701b002d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - google-api-python-client >=1.7.12
    - oauth2client >=4.0.0
    - pyyaml >=3.0
    - pyOpenSSL >=19.1.0

test:
  imports:
    - pydrive2
    - pydrive2.auth
    - pydrive2.drive
    - pydrive2.files
    - pydrive2.settings

about:
  home: https://github.com/iterative/PyDrive2
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: >
    Google Drive API Python wrapper library. Actively maintained fork of PyDrive.
  doc_url: https://gsuitedevs.github.io/PyDrive/docs/build/html/index.html
  dev_url: https://github.com/iterative/PyDrive2

extra:
  recipe-maintainers:
    - efiop
    - shcheklein
