{% set name = "PyDrive2" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bbdc8d2e002e4f87d20f9bd849f93fd6589ebb40dad97f94b6f382b4ffd6b3c1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >=3.6
    - google-api-python-client >=1.12.5
    - six >=1.13.0
    - oauth2client >=4.0.0
    - pyyaml >=3.0
    - pyOpenSSL >=19.1.0
    - fsspec >=2021.7.0
    - tqdm >=4.0.0  # for fsspec
    - funcy <2  # for fsspec
    - appdirs >=1.4.3  # for fsspec

test:
  imports:
    - pydrive2
    - pydrive2.auth
    - pydrive2.drive
    - pydrive2.files
    - pydrive2.settings
    - pydrive2.fs

about:
  home: https://github.com/iterative/PyDrive2
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: >
    Google Drive API Python wrapper library. Actively maintained fork of PyDrive.
  doc_url: https://gsuitedevs.github.io/PyDrive/docs/build/html/index.html
  dev_url: https://github.com/iterative/PyDrive2

extra:
  recipe-maintainers:
    - efiop
    - shcheklein
